# Generated by Django 4.0.1 on 2022-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Photography', 'Photography'), ('Massage', 'Massage'), ('Sexting', 'Sexting'), ('Mating', 'Mating'), ('Scrubbing', 'Scrubbing'), ('Hiking', 'Hiking'), ('More Than 1', 'More Than 1')], max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('Service_me_at', models.TimeField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, max_length=40, null=True)),
                ('created', models.TimeField(auto_now=True)),
            ],
        ),
    ]
