# Generated by Django 4.0.1 on 2022-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reach_me_via',
            field=models.CharField(choices=[('Phone call', 'Call Me'), ('Massage', 'Massage Me'), ('WhatsApp', 'WhatsApp Me'), ('Live Chat', 'Live Chat'), ('Any', 'Any')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Massage', 'Massage'), ('Sexting', 'Sexting'), ('Mating', 'Mating'), ('Scrubbing', 'Scrubbing'), ('Hiking', 'Hiking'), ('I can Explain', 'I can Explain')], max_length=40),
        ),
    ]
